// Copyright 2017-2022 @zcloak/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @zcloak/dev

export const packageInfo = { name: '@zcloak/dev', path: 'auto', type: 'auto', version: '0.0.0' };
